name: Build NDS

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    steps:
      - uses: actions/checkout@v4
      - name: Compila
        run: make
      - name: Salva la ROM
        uses: actions/upload-artifact@v4
        with:
          name: battle-royale-ds
          path: "*.nds"
